### ISSUE TITLE
подсветка активного пункта розового меню  не работает

### ISSUE THREAD

**Issue by vex2k** [srgg6701/Visavi#11]
подсветка активного пункта розового меню  не работает - зайдя например в http://new.vizavi-salon.spb.ru/lazernaya-epilyatsiya/2-uncategorised/5-epilation.html или ее подкатегорию фон кнопки с лазерной эпиляцией не становится темнее как при наведении на нее.

**Comment by srgg6701** [comment]
Это в ТЗ было?

**Comment by vex2k** [comment]
Баг, было на макетах. в мобильных версиях однозначно.
