### ISSUE TITLE
В мобильной версии ссылку "показать скрыть все содержимое " оформи в виде кнопки пожалуйста

### ISSUE THREAD

**Issue by vex2k** [srgg6701/Visavi#15]
В мобильной версии ссылку "показать скрыть все содержимое " оформи в виде кнопки пожалуйста, попасть по ссылке пальцем очень сложно. Она не работает . примеры скриншотов в почте. ты говорил что сделаешь сам, но активная ссылка это не кнопка, попасть в нее нереально. Нужна именно кнопка.

**Comment by srgg6701** [comment]
Сделал. Непонятно только, куда делся заголовок меню под нею. У меня на локальном есть. Кто-то в модуле полазил?
