### ISSUE TITLE
Ошибка при отображении не маркированного списка

### ISSUE THREAD

**Issue by vex2k** [srgg6701/Visavi#8]
http://new.vizavi-salon.spb.ru/index.php/lazernaya-epilyatsiya-podmyshek

**Comment by srgg6701** [comment]
Никакой ошибки там нет.
Нужно добавить к тегу UL класс "block".
А ещё неплохо было бы найти человека, у которого есть немножко мозга, чтобы он не вставлял тупо контент из word'а, а хоть немного его причёсывал, т.е., удалял кучу мусорных тегов.
Или не надо? И так сойдёт?

**Comment by vex2k** [comment]
Разобрался, вопрос снят, спасибо за объяснение. про мусорные теги ты про justify писал в данном случае?
