### ISSUE TITLE
Внешний вид заголовка h1 цвет и отсупы от хлебных крошек отличаются от макета

### ISSUE THREAD

**Issue by vex2k** [srgg6701/Visavi#9]
![bug h1 breadcrumbs](https://cloud.githubusercontent.com/assets/7836205/5991762/aff74592-aa1d-11e4-8ffe-84a45e630c5f.jpg)

Внешний вид заголовка h1 цвет и отсупы от хлебных крошек отличаются от макета

**Comment by srgg6701** [comment]
Разгадка жуткой тайны всё та же: https://github.com/srgg6701/Visavi/issues/8
Сообразите?

**Comment by vex2k** [comment]
По заголовку h1 - поменяй пожалуйста чтобы заголовки h1 h2 h3 у обычных статей и новостей были как на макете без прописывания стилей отдельно каждому заголвоку. Т.е. что бы уменьшить как можно больше работу контентщиков - таких страниц большинство - нет смысла вручную тратить каждый раз на это время.

**Comment by vex2k** [comment]
Проблема все еще не решена или я ошибаюсь?

**Comment by srgg6701** [comment]
Исправил посредством модификации стилей.
